### PR TITLE
Use curl Instead Of wget

### PR DESCRIPTION
**Pull request by kn1kn1**
I recently got error with wget, I changed wget to curl. Please refer to my ci logs.

wget: https://circleci.com/gh/kn1kn1/language-context-free/106
curl: https://circleci.com/gh/kn1kn1/language-context-free/108

### CODE REVIEW

**Comment by Arcanemagus** [comment]
The issue is that the `wget` installed on the image is out of date and fails to validate the SSL cert, we've been working around this on the linter packages with the following:

```yaml
 dependencies:
  pre:
    # Force updating wget due to the current containers being too out of date
    - sudo apt-get update
    - sudo apt-get install wget
```

@levlaz Could the images possible be updated/fixed, or should we keep using workarounds like forcing an update to `wget` or switching to `curl`?

**Comment by Arcanemagus** [comment]
Since CircleCI builds are broken until this is merged or their containers are updated can this be reviewed?

**Comment by Arcanemagus** [comment]
If the workaround we are using in the linter builds (force update of `wget` first) is preferred I can throw a PR for that up.

**Comment by mnquintana** [comment]
This seems totally fine to me (and we're already using `curl` in the Travis script anyway), just one question – is the `-L` flag necessary here?

**Comment by kn1kn1** [comment]
may not be necessary but build-package.sh has the flag.
https://github.com/atom/ci/blob/master/build-package.sh#L26

**Comment by mnquintana** [comment]
Looks good to me – thanks for this! :guitar:

**Pull request merged**
