### PR TITLE
Use glob instead of directory when linting with standard

### PR DESCRIPTION
**Pull request by mnquintana**
Refs https://github.com/atom/toggle-quotes/pull/26#issuecomment-135603697
Refs https://github.com/feross/standard/issues/135

/cc @maxbrunsfeld

### CODE REVIEW

**Comment by lee-dohm** [comment]
Sorry I don't have better context, but I have a couple questions:

1. Should the CoffeeLint and ESLint sections change their patterns as well?
1. Will this be used for CI of npm modules like [first-mate](https://github.com/atom/first-mate)? If so, should `src/**/*.js` also be included in addition to `lib/**/*.js`?

**Comment by mnquintana** [comment]
> Should the CoffeeLint and ESLint sections change their patterns as well?

Nope, this is just a unique quirk of Standard - it doesn't work with directory names, only with globs. ¯\\_(ツ)_/¯

> Will this be used for CI of npm modules like first-mate? If so, should src/**/*.js also be included in addition to lib/**/*.js?

I think this is just for Atom packages at the moment.

**Comment by lee-dohm** [comment]
Sounds good! :rocket:

**Comment by maxbrunsfeld** [comment]
Thanks!

**Pull request merged**
