### PR TITLE
add atom path to PATH on travis linux

### LINKED ISSUE #81: apm and atom not added to the PATH on Travis
Running the script on Travis the `apm` and `atom` are available in `~/atom/usr/bin` but they are not added to the `PATH`.

`apm` can be used within a `npm` script, as on Travis the home folder is part of the npm bin path.
But it's not possible to execute `apm` nor `atom` directly as a script.

`.travis.yml`example:
```yaml
script:
  - curl -s -O https://raw.githubusercontent.com/atom/ci/master/build-package.sh
  - chmod u+x build-package.sh
  - ./build-package.sh
  - atom -v
```
It fails with the error `sh: 1: atom: not found`.

This can be solved with `export PATH=$PATH:~/atom/usr/bin`

### PR DESCRIPTION
**Pull request by UziTech**
This will help a lot with people setting up semantic-release for apm packages

fixes #81

### CODE REVIEW

**Comment by Arcanemagus** [comment]
Specifically for `semantic-release` the only requirement is `apm` is available, would this be better done by mimicking the `$PATH` enhancement already being done on the other platforms?

**Comment by UziTech** [comment]
`atom` and `apm` are in the same folder so this would allow both to be used. I just copied the `$PATH` assignment from [`osx`](https://github.com/atom/ci/blob/d8d3637c4289866cc2a8a794e5933dcb6d91369b/build-package.sh#L25) and changed the path to reflect the `$ATOM_SCRIPT_PATH` folder.

**Comment by Arcanemagus** [comment]
Interestingly, it looks like you were the one that added the other more specific path: https://github.com/atom/ci/pull/71 😆

**Comment by UziTech** [comment]
Ya now that I think about it, it was strange that it was working in Linux

**Pull request merged**
