### PR TITLE
Revert changes from #43

### PR DESCRIPTION
**Pull request by Arcanemagus**
Reverts the changes from #43 per https://github.com/atom/ci/pull/43#issuecomment-231045185.

### CODE REVIEW

**Comment by Arcanemagus** [comment]
@joefitzgerald, @thomasjo Any reason this hasn't been merged yet? The changes in #43 were supposedly causing issues with packages, and have not yet been reverted...

**Comment by joefitzgerald** [comment]
@thomasjo you merged #43, what do you think?

**Comment by thomasjo** [comment]
I don't recall anyone saying this caused any issues. I'm not against reverting it, but now we're at least consistent across platforms. My point was always that we should be consistent.

The CI scripts are a royal mess and desperately needs to be refactored... it's on my list, but likely won't happen until September. I'm leaning towards leaving things as they are now unless someone can point me to actual evidence that what we have now is causing problems. I'm not looking for theoretical problems, **only** real and current problems.

**Comment by Arcanemagus** [comment]
Okay, closing this then 😉.

**Comment by Arcanemagus** [comment]
As a note, #49 essentially did this reversion if the flag to use the bundled `node` is enabled (which it is by default).

**Pull request closed without merging**
