### PR TITLE
Some cleanup

### PR DESCRIPTION
**Pull request by Arcanemagus**
Functional changes:

* Show Atom and `apm` versions on CircleCI
* Run `apm clean` before `apm install` on CircleCI

Cosmetic changes:

* Separate the Travis-CI and AppVeyor configs into sections, making it clearer where potential changes would likely be
* Add a comment to the AppVeyor config explaining what the Node.js install is for

### CODE REVIEW

**Comment by joefitzgerald** [comment]
LGTM 👍

**Comment by Arcanemagus** [comment]
Rebased on the current `master`.

**Comment by joefitzgerald** [comment]
Still LGTM.

**Comment by Arcanemagus** [comment]
@thomasjo Are there any changes required?

**Comment by lee-dohm** [comment]
Thanks for contributing!

**Comment by thomasjo** [comment]
I don't love the `### header-like comments ###`, but that's such a minor thing.

Thanks for contributing @Arcanemagus 🙇

**Comment by Arcanemagus** [comment]
@thomasjo If you have a better idea for how to show that to somebody who may be new to CI scripts I'd be happy to put up a PR for it 😉.

**Pull request merged**
